%LOAD DATA
%load the new images as an image datastore
imdsTrain = imageDatastore('data/train images', ...
    'IncludeSubfolders',true, ...
    'LabelSource','foldernames'); 
imdsValidation = imageDatastore('data/validation images', ...
    'IncludeSubfolders',true, ...
    'LabelSource','foldernames');
imdsTest = imageDatastore('data/test images', ...
    'IncludeSubfolders',true, ...
    'LabelSource','foldernames'); 
